version: '3'

services:
  api:
    build: ./api
    ports:
      - 4001:4001
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - GRAPHQL_LISTEN_PORT=4001
      - GRAPHQL_URI=http://api:4001/graphql
  ui:
    build: ./web-react
    ports:
      - 3000:3000
    environment:
      - CI=true
      - REACT_APP_GRAPHQL_URI=/graphql
      - PROXY=http://api:4001/graphql
    links:
      - api
    depends_on:
      - api
